# This rule is not used by the project optipod itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to optipod.optipod.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: optipod
    app.kubernetes.io/managed-by: kustomize
  name: optimizationpolicy-viewer-role
rules:
- apiGroups:
  - optipod.optipod.io
  resources:
  - optimizationpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - optipod.optipod.io
  resources:
  - optimizationpolicies/status
  verbs:
  - get
